#!/bin/bash
### Job Name
#PBS -N NewCarbon0.15
### Project code
#PBS -A UMIT0025
#PBS -l walltime=12:00:00
#PBS -q economy
### Merge output and error files
#PBS -j oe
### Select 2 nodes with 36 CPUs each for a total of 72 MPI processes
#PBS -l select=7:ncpus=36:mpiprocs=36
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M myoungs@mit.edu

#rm *.ckpt*.*ta

pmeta=$( ls -t pickup.*.meta |head -1 )
plabel=$( echo $pmeta | sed 's/pickup.\(.*\).meta/\1/' )

# strip from data
sed -i.bak -n -e '/pickupSuff/I!p' data

if [ "${plabel:0:1}" == "c" ]
then
    # we have a partial checkpoint
    iter=$( grep timeStepNumber $pmeta | sed -e 's/.*\[ \(.*\) \];/\1/' )
    extra="\n pickupSuff='$plabel',"
else
    iter=$plabel
fi

# update iteration number
sed -i.bak -e "s/nIter0=\(.*\)/nIter0=$iter,$extra/I" data


module load impi
mpirun -n 240 ./mitgcmuv
